---
- name: Bootstrap AWX for PowerScale Demo
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx

  vars:
    # Update these three variables with your Minikube deployment details!
    controller_host: "http://127.0.0.1:41839"
    controller_username: "admin"
    controller_password: ""
    controller_validate_certs: false

  environment:
    CONTROLLER_HOST: "{{ controller_host }}"
    CONTROLLER_USERNAME: "{{ controller_username }}"
    CONTROLLER_PASSWORD: "{{ controller_password }}"
    CONTROLLER_VERIFY_SSL: "{{ controller_validate_certs | string }}"

  tasks:
    - name: 1. Create PowerScale Machine Credential
      credential:
        name: "PowerScale_API_Creds"
        credential_type: "Machine"
        organization: "Default"
        inputs:
          username: "root"
          password: "YourPowerScalePassword" # Update when you build the real PowerScale 

    - name: 2. Create Demo Inventory
      inventory:
        name: "PowerScale Demo Inventory"
        organization: "Default"

    - name: 3. Add PowerScale Clusters to Inventory
      host:
        name: "site-b.isilon.local" # The target cluster we will fail over to
        inventory: "PowerScale Demo Inventory"
        variables:
          ansible_connection: local # PowerScale modules use REST API locally from AWX

    - name: 4. Create GitHub Project for Payload
      project:
        name: "PowerScale Failover Playbooks"
        organization: "Default"
        scm_type: git
        # Ensure you have pushed your repository to this URL!
        scm_url: "https://github.com/alisoleah/-powerscale-demo-k8s.git" # Update 'galala' if your GitHub username is different
        scm_update_on_launch: true
        # update_project: false

    - name: 5. Create Failover Job Template
      job_template:
        name: "EXECUTE: Site A to Site B NFS Failover"
        project: "PowerScale Failover Playbooks"
        inventory: "PowerScale Demo Inventory"
        playbook: "playbooks/failover.yml"
        credentials:
          - "PowerScale_API_Creds"
        ask_variables_on_launch: true
        extra_vars:
          target_cluster: "site-b.isilon.local"
          synciq_policy: "NFS_Demo_Policy"